language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer install --prefer-source --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml

after_script:
   - php vendor/bin/coveralls
